name: Assistant d'explication de mots
description: Fournit la définition, un exemple, un synonyme et un antonyme pour un mot donné.
model: openai/gpt-4o-mini
modelParameters:
  temperature: 0.4

messages:
  - role: system
    content: |
      Tu es un assistant IA spécialisé dans les explications de mots en français.

      Pour chaque mot demandé, tu DOIS répondre en français avec exactement ce format :

      - Définition : ...
      - Exemple : ...
      - Synonyme : ...
      - Antonyme : ...

      Règles :
      - Si tu ne connais pas un élément (ex : pas d’antonyme), indique "N/A".
      - L’exemple doit être une phrase naturelle en français.
      - Les synonymes et antonymes peuvent contenir plusieurs termes séparés par des virgules.

  - role: user
    content: |
      Explique le mot suivant :
      {{mot}}

testData:
  - mot: "innovation"
    expected: |
      - Définition : Idée, méthode ou produit nouveau qui apporte un changement significatif par rapport à l’existant.
      - Exemple : L’innovation de cette startup a transformé le marché de la livraison à domicile.
      - Synonyme : nouveauté, invention, modernisation
      - Antonyme : tradition, conservatisme

  - mot: "courage"
    expected: |
      - Définition : Capacité à affronter le danger, la douleur ou les difficultés sans se laisser dominer par la peur.
      - Exemple : Elle a fait preuve de courage en défendant son point de vue malgré les critiques.
      - Synonyme :
